In [1]:
import pandas as pd
import numpy as np

To understand what's going on here, read [this article about character encodings](http://www.joelonsoftware.com/articles/Unicode.html). 

To install `uchardet`, do the following:
```
$ brew install uchardet
```

In [3]:
!tail baby_names.csv

1920,Mary,Dorothy,Helen,Margaret,Ruth,John,William,Robert,James,Charles
1919,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Charles
1918,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Charles
1917,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
1916,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
1915,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
1914,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
,,,,,,,,,,
,,,,,,,,,,
"Copyright ï¿½ 2014, SAS Institute Inc., Cary, NC, USA. All Rights Reserved. ",,,,,,,,,,

In [4]:
!uchardet baby_names.csv

windows-1252

In [5]:
baby_names = pd.read_csv('baby_names.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 10: invalid start byte

In [6]:
!uchardet baby_names.csv

windows-1252

In [7]:
baby_names = pd.read_csv('baby_names.csv', encoding='windows-1252')
baby_names.head(15)

,Top Five Baby Names,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Source: http://www.ssa.gov/oact/babynames/top5...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Note: data includes top five male and female b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Females,NaN,NaN,NaN,NaN,Males,NaN,NaN,NaN,NaN
8,Year,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5
9,2013,Sophia,Emma,Olivia,Isabella,Ava,Noah,Liam,Jacob,Mason,William
10,2012,Sophia,Emma,Isabella,Olivia,Ava,Jacob,Mason,Ethan,Noah,William
11,2011,Sophia,Isabella,Emma,Olivia,Ava,Jacob,Mason,William,Jayden,Noah
12,2010,Isabella,Sophia,Emma,Olivia,Ava,Jacob,Ethan,Michael,Jayden,William
13,2009,Isabella,Emma,Olivia,Sophia,Ava,Jacob,Ethan,Michael,Alexander,William
14,2008,Emma,Isabella,Emily,Olivia,Ava,Jacob,Michael,Ethan,Joshua,Daniel

In [8]:
!head 'baby_names.csv'

Top Five Baby Names,,,,,,,,,,
Source: http://www.ssa.gov/oact/babynames/top5names.html,,,,,,,,,,
Note: data includes top five male and female baby names between 1914 and 2013,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,Females,,,,,Males,,,,
Year,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5

In [9]:
baby_names.tail()

,Top Five Baby Names,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
107,1915,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
108,1914,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,"Copyright Â© 2014, SAS Institute Inc., Cary, NC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

So we can look at our data and see the nans, but we should tell pandas to just ignore those rows that aren't actually part of our data

We can pass in more kwargs to the csv_read function

In [10]:
baby_names = pd.read_csv('baby_names.csv', encoding='windows-1252', header=[8,9], skip_footer=3)

/Users/james/src/github.com/tiyd-python-2015-08/course-resources/.direnv/python-3.4.3/lib/python3.4/site-packages/pandas/io/parsers.py:648: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skip_footer; you can avoid this warning by specifying engine='python'.
  ParserWarning)

In [11]:
baby_names

,Unnamed: 0_level_0,Females,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Males,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,Unnamed: 10_level_0
,Year,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5,Rank 1,Rank 2,Rank 3,Rank 4,Rank 5
0,2013,Sophia,Emma,Olivia,Isabella,Ava,Noah,Liam,Jacob,Mason,William
1,2012,Sophia,Emma,Isabella,Olivia,Ava,Jacob,Mason,Ethan,Noah,William
2,2011,Sophia,Isabella,Emma,Olivia,Ava,Jacob,Mason,William,Jayden,Noah
3,2010,Isabella,Sophia,Emma,Olivia,Ava,Jacob,Ethan,Michael,Jayden,William
4,2009,Isabella,Emma,Olivia,Sophia,Ava,Jacob,Ethan,Michael,Alexander,William
5,2008,Emma,Isabella,Emily,Olivia,Ava,Jacob,Michael,Ethan,Joshua,Daniel
6,2007,Emily,Isabella,Emma,Ava,Madison,Jacob,Michael,Ethan,Joshua,Daniel
7,2006,Emily,Emma,Madison,Isabella,Ava,Jacob,Michael,Joshua,Ethan,Matthew
8,2005,Emily,Emma,Madison,Abigail,Olivia,Jacob,Michael,Joshua,Matthew,Ethan
9,2004,Emily,Emma,Madison,Olivia,Hannah,Jacob,Michael,Joshua,Matthew,Ethan
10,2003,Emily,Emma,Madison,Hannah,Olivia,Jacob,Michael,Joshua,Matthew,Andrew
11,2002,Emily,Madison,Hannah,Emma,Alexis,Jacob,Michael,Joshua,Matthew,Ethan
12,2001,Emily,Madison,Hannah,Ashley,Alexis,Jacob,Michael,Matthew,Joshua,Christopher
13,2000,Emily,Hannah,Madison,Ashley,Sarah,Jacob,Michael,Matthew,Joshua,Christopher
14,1999,Emily,Hannah,Alexis,Sarah,Samantha,Jacob,Michael,Matthew,Joshua,Nicholas
15,1998,Emily,Hannah,Samantha,Ashley,Sarah,Michael,Jacob,Matthew,Joshua,Christopher
16,1997,Emily,Jessica,Ashley,Sarah,Hannah,Michael,Jacob,Matthew,Christopher,Joshua
17,1996,Emily,Jessica,Ashley,Sarah,Samantha,Michael,Matthew,Jacob,Christopher,Joshua
18,1995,Jessica,Ashley,Emily,Samantha,Sarah,Michael,Matthew,Christopher,Jacob,Joshua
19,1994,Jessica,Ashley,Emily,Samantha,Sarah,Michael,Christopher,Matthew,Joshua,Tyler
20,1993,Jessica,Ashley,Sarah,Samantha,Emily,Michael,Christopher,Matthew,Joshua,Tyler
21,1992,Ashley,Jessica,Amanda,Brittany,Sarah,Michael,Christopher,Matthew,Joshua,Andrew
22,1991,Ashley,Jessica,Brittany,Amanda,Samantha,Michael,Christopher,Matthew,Joshua,Andrew
23,1990,Jessica,Ashley,Brittany,Amanda,Samantha,Michael,Christopher,Matthew,Joshua,Daniel
24,1989,Jessica,Ashley,Brittany,Amanda,Sarah,Michael,Christopher,Matthew,Joshua,David
25,1988,Jessica,Ashley,Amanda,Sarah,Jennifer,Michael,Christopher,Matthew,Joshua,Andrew
26,1987,Jessica,Ashley,Amanda,Jennifer,Sarah,Michael,Christopher,Matthew,Joshua,David
27,1986,Jessica,Ashley,Amanda,Jennifer,Sarah,Michael,Christopher,Matthew,Joshua,David
28,1985,Jessica,Ashley,Jennifer,Amanda,Sarah,Michael,Christopher,Matthew,Joshua,Daniel
29,1984,Jennifer,Jessica,Ashley,Amanda,Sarah,Michael,Christopher,Matthew,Joshua,David
...,...,...,...,...,...,...,...,...,...,...,...
70,1943,Mary,Barbara,Patricia,Linda,Carol,James,Robert,John,William,Richard
71,1942,Mary,Barbara,Patricia,Linda,Carol,James,Robert,John,William,Richard
72,1941,Mary,Barbara,Patricia,Carol,Linda,James,Robert,John,William,Richard
73,1940,Mary,Barbara,Patricia,Judith,Betty,James,Robert,John,William,Richard
74,1939,Mary,Barbara,Patricia,Betty,Shirley,Robert,James,John,William,Richard
75,1938,Mary,Barbara,Patricia,Betty,Shirley,Robert,James,John,William,Richard
76,1937,Mary,Barbara,Patricia,Shirley,Betty,Robert,James,John,William,Richard
77,1936,Mary,Shirley,Barbara,Betty,Patricia,Robert,James,John,William,Richard
78,1935,Mary,Shirley,Barbara,Betty,Patricia,Robert,James,John,William,Richard
79,1934,Mary,Betty,Barbara,Shirley,Dorothy,Robert,James,John,William,Richard
80,1933,Mary,Betty,Barbara,Dorothy,Joan,Robert,James,John,William,Richard
81,1932,Mary,Betty,Barbara,Dorothy,Joan,Robert,James,John,William,Richard
82,1931,Mary,Betty,Dorothy,Barbara,Joan,Robert,James,John,William,Richard
83,1930,Mary,Betty,Dorothy,Helen,Margaret,Robert,James,John,William,Richard
84,1929,Mary,Betty,Dorothy,Helen,Margaret,Robert,James,John,William,Charles
85,1928,Mary,Betty,Dorothy,Helen,Margaret,Robert,John,James,William,Charles
86,1927,Mary,Dorothy,Betty,Helen,Margaret,Robert,John,James,William,Charles
87,1926,Mary,Dorothy,Betty,Helen,Margaret,Robert,John,James,William,Charles
88,1925,Mary,Dorothy,Betty,Helen,Margaret,Robert,John,William,James,Charles
89,1924,Mary,Dorothy,Helen,Betty,Margaret,Robert,John,William,James,Charles
90,1923,Mary,Dorothy,Helen,Margaret,Betty,John,Robert,William,James,Charles
91,1922,Mary,Dorothy,Helen,Margaret,Ruth,John,Robert,William,James,Charles
92,1921,Mary,Dorothy,Helen,Margaret,Ruth,John,Robert,William,James,Charles
93,1920,Mary,Dorothy,Helen,Margaret,Ruth,John,William,Robert,James,Charles
94,1919,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Charles
95,1918,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Charles
96,1917,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
97,1916,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
98,1915,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph
99,1914,Mary,Helen,Dorothy,Margaret,Ruth,John,William,James,Robert,Joseph

We need to be clear about how our columns relate to each other. We can pass in a structure like this to a method of the dataframe to re-index the fields

```
[('female', '1'), ('female', '2'), ('female', '3')... ('male', '1'), ('male', '2')...]
```

In [13]:
genders = ('female', 'male')
ranks = ('1', '2', '3', '4', '5')
columns = [(gender, rank) for gender in genders for rank in ranks]
index = pd.MultiIndex.from_tuples(columns)
index

MultiIndex(levels=[['female', 'male'], ['1', '2', '3', '4', '5']],
           labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [17]:
baby_names = pd.read_csv('baby_names.csv', encoding='windows-1252',
                         header=9, index_col=0, 
                         names=index)

In [18]:
baby_names

                                                      female            \
                                                           1         2
2013                                                  Sophia      Emma
2012                                                  Sophia      Emma
2011                                                  Sophia  Isabella
2010                                                Isabella    Sophia
2009                                                Isabella      Emma
2008                                                    Emma  Isabella
2007                                                   Emily  Isabella
2006                                                   Emily      Emma
2005                                                   Emily      Emma
2004                                                   Emily      Emma
2003                                                   Emily      Emma
2002                                                   Emily   Madison
2001                                                   Emily   Madison
2000                                                   Emily    Hannah
1999                                                   Emily    Hannah
1998                                                   Emily    Hannah
1997                                                   Emily   Jessica
1996                                                   Emily   Jessica
1995                                                 Jessica    Ashley
1994                                                 Jessica    Ashley
1993                                                 Jessica    Ashley
1992                                                  Ashley   Jessica
1991                                                  Ashley   Jessica
1990                                                 Jessica    Ashley
1989                                                 Jessica    Ashley
1988                                                 Jessica    Ashley
1987                                                 Jessica    Ashley
1986                                                 Jessica    Ashley
1985                                                 Jessica    Ashley
1984                                                Jennifer   Jessica
...                                                      ...       ...
1940                                                    Mary   Barbara
1939                                                    Mary   Barbara
1938                                                    Mary   Barbara
1937                                                    Mary   Barbara
1936                                                    Mary   Shirley
1935                                                    Mary   Shirley
1934                                                    Mary     Betty
1933                                                    Mary     Betty
1932                                                    Mary     Betty
1931                                                    Mary     Betty
1930                                                    Mary     Betty
1929                                                    Mary     Betty
1928                                                    Mary     Betty
1927                                                    Mary   Dorothy
1926                                                    Mary   Dorothy
1925                                                    Mary   Dorothy
1924                                                    Mary   Dorothy
1923                                                    Mary   Dorothy
1922                                                    Mary   Dorothy
1921                                                    Mary   Dorothy
1920                                                    Mary   Dorothy
1919                                                    Mary     Helen
1918                                                    Mary     Helen
1917                                                    Mary     Helen
1916                                                    Mary     Helen
1915                                                    Mary     Helen
1914                                                    Mary     Helen
NaN                                                      NaN       NaN
NaN                                                      NaN       NaN
Copyright Â© 2014, SAS Institute Inc., Cary, NC,...       NaN       NaN

                                                                        \
                                                           3         4
2013                                                  Olivia  Isabella
2012                                                Isabella    Olivia
2011                                                    Emma    Olivia
2010                                                    Emma    Olivia
2009                                                  Olivia    Sophia
2008                                                   Emily    Olivia
2007                                                    Emma       Ava
2006                                                 Madison  Isabella
2005                                                 Madison   Abigail
2004                                                 Madison    Olivia
2003                                                 Madison    Hannah
2002                                                  Hannah      Emma
2001                                                  Hannah    Ashley
2000                                                 Madison    Ashley
1999                                                  Alexis     Sarah
1998                                                Samantha    Ashley
1997                                                  Ashley     Sarah
1996                                                  Ashley     Sarah
1995                                                   Emily  Samantha
1994                                                   Emily  Samantha
1993                                                   Sarah  Samantha
1992                                                  Amanda  Brittany
1991                                                Brittany    Amanda
1990                                                Brittany    Amanda
1989                                                Brittany    Amanda
1988                                                  Amanda     Sarah
1987                                                  Amanda  Jennifer
1986                                                  Amanda  Jennifer
1985                                                Jennifer    Amanda
1984                                                  Ashley    Amanda
...                                                      ...       ...
1940                                                Patricia    Judith
1939                                                Patricia     Betty
1938                                                Patricia     Betty
1937                                                Patricia   Shirley
1936                                                 Barbara     Betty
1935                                                 Barbara     Betty
1934                                                 Barbara   Shirley
1933                                                 Barbara   Dorothy
1932                                                 Barbara   Dorothy
1931                                                 Dorothy   Barbara
1930                                                 Dorothy     Helen
1929                                                 Dorothy     Helen
1928                                                 Dorothy     Helen
1927                                                   Betty     Helen
1926                                                   Betty     Helen
1925                                                   Betty     Helen
1924                                                   Helen     Betty
1923                                                   Helen  Margaret
1922                                                   Helen  Margaret
1921                                                   Helen  Margaret
1920                                                   Helen  Margaret
1919                                                 Dorothy  Margaret
1918                                                 Dorothy  Margaret
1917                                                 Dorothy  Margaret
1916                                                 Dorothy  Margaret
1915                                                 Dorothy  Margaret
1914                                                 Dorothy  Margaret
NaN                                                      NaN       NaN
NaN                                                      NaN       NaN
Copyright Â© 2014, SAS Institute Inc., Cary, NC,...       NaN       NaN

                                                                 male  \
                                                           5        1
2013                                                     Ava     Noah
2012                                                     Ava    Jacob
2011                                                     Ava    Jacob
2010                                                     Ava    Jacob
2009                                                     Ava    Jacob
2008                                                     Ava    Jacob
2007                                                 Madison    Jacob
2006                                                     Ava    Jacob
2005                                                  Olivia    Jacob
2004                                                  Hannah    Jacob
2003                                                  Olivia    Jacob
2002                                                  Alexis    Jacob
2001                                                  Alexis    Jacob
2000                                                   Sarah    Jacob
1999                                                Samantha    Jacob
1998                                                   Sarah  Michael
1997                                                  Hannah  Michael
1996                                                Samantha  Michael
1995                                                   Sarah  Michael
1994                                                   Sarah  Michael
1993                                                   Emily  Michael
1992                                                   Sarah  Michael
1991                                                Samantha  Michael
1990                                                Samantha  Michael
1989                                                   Sarah  Michael
1988                                                Jennifer  Michael
1987                                                   Sarah  Michael
1986                                                   Sarah  Michael
1985                                                   Sarah  Michael
1984                                                   Sarah  Michael
...                                                      ...      ...
1940                                                   Betty    James
1939                                                 Shirley   Robert
1938                                                 Shirley   Robert
1937                                                   Betty   Robert
1936                                                Patricia   Robert
1935                                                Patricia   Robert
1934                                                 Dorothy   Robert
1933                                                    Joan   Robert
1932                                                    Joan   Robert
1931                                                    Joan   Robert
1930                                                Margaret   Robert
1929                                                Margaret   Robert
1928                                                Margaret   Robert
1927                                                Margaret   Robert
1926                                                Margaret   Robert
1925                                                Margaret   Robert
1924                                                Margaret   Robert
1923                                                   Betty     John
1922                                                    Ruth     John
1921                                                    Ruth     John
1920                                                    Ruth     John
1919                                                    Ruth     John
1918                                                    Ruth     John
1917                                                    Ruth     John
1916                                                    Ruth     John
1915                                                    Ruth     John
1914                                                    Ruth     John
NaN                                                      NaN      NaN
NaN                                                      NaN      NaN
Copyright Â© 2014, SAS Institute Inc., Cary, NC,...       NaN      NaN

                                                                              \
                                                              2            3
2013                                                       Liam        Jacob
2012                                                      Mason        Ethan
2011                                                      Mason      William
2010                                                      Ethan      Michael
2009                                                      Ethan      Michael
2008                                                    Michael        Ethan
2007                                                    Michael        Ethan
2006                                                    Michael       Joshua
2005                                                    Michael       Joshua
2004                                                    Michael       Joshua
2003                                                    Michael       Joshua
2002                                                    Michael       Joshua
2001                                                    Michael      Matthew
2000                                                    Michael      Matthew
1999                                                    Michael      Matthew
1998                                                      Jacob      Matthew
1997                                                      Jacob      Matthew
1996                                                    Matthew        Jacob
1995                                                    Matthew  Christopher
1994                                                Christopher      Matthew
1993                                                Christopher      Matthew
1992                                                Christopher      Matthew
1991                                                Christopher      Matthew
1990                                                Christopher      Matthew
1989                                                Christopher      Matthew
1988                                                Christopher      Matthew
1987                                                Christopher      Matthew
1986                                                Christopher      Matthew
1985                                                Christopher      Matthew
1984                                                Christopher      Matthew
...                                                         ...          ...
1940                                                     Robert         John
1939                                                      James         John
1938                                                      James         John
1937                                                      James         John
1936                                                      James         John
1935                                                      James         John
1934                                                      James         John
1933                                                      James         John
1932                                                      James         John
1931                                                      James         John
1930                                                      James         John
1929                                                      James         John
1928                                                       John        James
1927                                                       John        James
1926                                                       John        James
1925                                                       John      William
1924                                                       John      William
1923                                                     Robert      William
1922                                                     Robert      William
1921                                                     Robert      William
1920                                                    William       Robert
1919                                                    William        James
1918                                                    William        James
1917                                                    William        James
1916                                                    William        James
1915                                                    William        James
1914                                                    William        James
NaN                                                         NaN          NaN
NaN                                                         NaN          NaN
Copyright Â© 2014, SAS Institute Inc., Cary, NC,...          NaN          NaN


                                                              4            5
2013                                                      Mason      William
2012                                                       Noah      William
2011                                                     Jayden         Noah
2010                                                     Jayden      William
2009                                                  Alexander      William
2008                                                     Joshua       Daniel
2007                                                     Joshua       Daniel
2006                                                      Ethan      Matthew
2005                                                    Matthew        Ethan
2004                                                    Matthew        Ethan
2003                                                    Matthew       Andrew
2002                                                    Matthew        Ethan
2001                                                     Joshua  Christopher
2000                                                     Joshua  Christopher
1999                                                     Joshua     Nicholas
1998                                                     Joshua  Christopher
1997                                                Christopher       Joshua
1996                                                Christopher       Joshua
1995                                                      Jacob       Joshua
1994                                                     Joshua        Tyler
1993                                                     Joshua        Tyler
1992                                                     Joshua       Andrew